### ISSUE TITLE
هزینه استفاده از API

### ISSUE THREAD

**Issue by m98** [Text-Mining/demo#12]
در وبسایت صفحه خاصی درباره نحوه محاسبه هزینه استفاده وجود ندارد و اینطور برداشت میشه که ‍API رایگان است. لطفا درباره هزینه‌ها شفاف سازی کنید

متشکرم

**Comment by ehsanasgarian** [comment]
مطابق بند 8 از «[قوانین و مقررات سایت](http://text-mining.ir/terms)» برای ای.پی.آی رایگان محدودیت به شرح ذیل درنظر گرفته شده:

> 8 - استفاده‌کنندگان رایگان از ای.پی.آی، حداکثر مجاز به ارسال روزی ۱۰۰ درخواست (فراخوانی) و در هر ثانیه یک درخواست و هر فراخوانی (درخواست) با طول ورودی متنی کمتر از 3000 کاراکتر (یونیکد) یا 6000 هزاربایت می‌باشند.


یعنی توجه داشته باشید که هر فراخوانی باید یک ثانیه با فراخوانی قبلی فاصله زمانی داشته باشد وگرنه تضمینی برای پاسخ وجود ندارد.
هر کلید ای.پی.آی رایگان که از [پنل توسعه دهندگان متن کاوی](https://app.text-mining.ir/) دریافت میکنید، در جلوی آن تاریخ انقضا نوشته شده است (مطابق تصویر پیوست شده) و فعلاً رویه کار سایت برای کلیدهای رایگان محدودیت 14 روزه است و بعد از آن میتوانید یک کلید رایگان دیگر تهیه بفرمایید.
در صورت نیاز به استفاده بیشتر از محدودیتهای لحاظ شده، لطفاً با ما از طریق [hi@text-mining.ir](mailto:hi@text-mining.ir) تماس بگیرید.

![image](https://user-images.githubusercontent.com/14190410/65022179-bc803380-d945-11e9-812c-93cd5844801f.png)

**Comment by m98** [comment]
خیلی ممنونم بابت پاسخ خوبتون
