### ISSUE TITLE
باز شدن کیبورد Numeric در کروم اندروید

### ISSUE THREAD

**Issue by GlassesPi** [Text-Mining/demo#7]
.در کروم ورژن 71، اندروید 8، برای تایپ‌کردن در صفحه‌ی اصلاح اشتباهات تایپی، لی‌اوت درست کیبورد باز نمی‌شود

![screenshot_20190110-150429](https://user-images.githubusercontent.com/30589130/50966132-463f4d80-14e9-11e9-8efe-8ca5c3fad5b1.png)
![screenshot_20190110-150425](https://user-images.githubusercontent.com/30589130/50966145-4ccdc500-14e9-11e9-965e-edbd6b4add38.png)

**Comment by ehsanasgarian** [comment]
برای سایر مرورگر ها هم همین مشکل در گوشی هست
