### ISSUE TITLE
محدودیت برای ورودی دمو

### ISSUE THREAD

**Issue by ehsanasgarian** [Text-Mining/demo#8]
طول ورودی (تعداد کاراکتر) باید کمتر از ۱۰۰۰ کاراکتر و 
تعداد محدود فراخوانی در واحد زمان از روی 
ip
 خاص مثلا روزانه ۱۰۰ درخواست

**Comment by Hameds** [comment]
<div dir="rtl">

این محدویت‌ها باید روی کد API  اعمال شود نه دمو

</div>
